import React, { useState, useRef, useEffect } from 'react';
import { Upload, FileText, Trash2, MessageSquare, Settings, Database, Cpu, CheckCircle, AlertCircle, Loader } from 'lucide-react';

const RAGApp = () => {
  const [documents, setDocuments] = useState([]);
  const [messages, setMessages] = useState([]);
  const [query, setQuery] = useState('');
  const [selectedModel, setSelectedModel] = useState('llama3');
  const [availableModels, setAvailableModels] = useState([
    'llama3', 'mistral', 'phi', 'gemma', 'neural-chat'
  ]);
  const [isProcessing, setIsProcessing] = useState(false);
  const [isQuerying, setIsQuerying] = useState(false);
  const [activeTab, setActiveTab] = useState('documents');
  const [vectorDBStatus, setVectorDBStatus] = useState({ indexed: 0, total: 0 });
  const fileInputRef = useRef(null);
  const messagesEndRef = useRef(null);

  useEffect(() => {
    messagesEndRef.current?.scrollIntoView({ behavior: 'smooth' });
  }, [messages]);

  const handleFileUpload = (event) => {
    const files = Array.from(event.target.files);
    const newDocs = files.map(file => ({
      id: Date.now() + Math.random(),
      name: file.name,
      size: file.size,
      type: file.type,
      status: 'uploaded',
      chunks: 0,
      embeddings: 0
    }));
    
    setDocuments([...documents, ...newDocs]);
    
    // Simulate processing
    newDocs.forEach((doc, index) => {
      setTimeout(() => {
        setIsProcessing(true);
        setTimeout(() => {
          setDocuments(prev => prev.map(d => 
            d.id === doc.id 
              ? { ...d, status: 'processing', chunks: 0 }
              : d
          ));
          
          // Simulate chunking
          setTimeout(() => {
            const chunks = Math.floor(Math.random() * 20) + 5;
            setDocuments(prev => prev.map(d => 
              d.id === doc.id 
                ? { ...d, chunks, status: 'embedding' }
                : d
            ));
            
            // Simulate embedding generation
            setTimeout(() => {
              setDocuments(prev => prev.map(d => 
                d.id === doc.id 
                  ? { ...d, embeddings: chunks, status: 'indexed' }
                  : d
              ));
              setVectorDBStatus(prev => ({
                indexed: prev.indexed + chunks,
                total: prev.total + chunks
              }));
              setIsProcessing(false);
            }, 1500);
          }, 1000);
        }, 500);
      }, index * 500);
    });
  };

  const handleDeleteDocument = (docId) => {
    const doc = documents.find(d => d.id === docId);
    if (doc && doc.embeddings) {
      setVectorDBStatus(prev => ({
        indexed: prev.indexed - doc.embeddings,
        total: prev.total - doc.embeddings
      }));
    }
    setDocuments(documents.filter(d => d.id !== docId));
  };

  const handleQuery = () => {
    if (!query.trim() || documents.length === 0) return;
    
    const userMessage = { id: Date.now(), role: 'user', content: query };
    setMessages([...messages, userMessage]);
    setQuery('');
    setIsQuerying(true);
    
    // Simulate retrieval and generation
    setTimeout(() => {
      const relevantDocs = documents.slice(0, 2).map(d => d.name).join(', ');
      const aiMessage = {
        id: Date.now() + 1,
        role: 'assistant',
        content: `Based on the retrieved context from ${relevantDocs}, here's the answer:\n\n${generateMockAnswer(query)}`,
        sources: documents.slice(0, 2).map(d => d.name),
        chunks: Math.floor(Math.random() * 3) + 2
      };
      setMessages(prev => [...prev, aiMessage]);
      setIsQuerying(false);
    }, 2000);
  };

  const generateMockAnswer = (question) => {
    const answers = [
      "This is a comprehensive answer generated by the local LLM using the retrieved context from your documents. The information has been extracted from the most relevant chunks in the vector database.",
      "According to the documents in the knowledge base, the answer involves multiple aspects that have been carefully analyzed. The LLM has synthesized information from several document chunks to provide this response.",
      "The retrieved context provides valuable insights into your question. After processing the relevant document segments, the model has generated this contextually accurate response."
    ];
    return answers[Math.floor(Math.random() * answers.length)];
  };

  const formatFileSize = (bytes) => {
    if (bytes < 1024) return bytes + ' B';
    if (bytes < 1024 * 1024) return (bytes / 1024).toFixed(1) + ' KB';
    return (bytes / (1024 * 1024)).toFixed(1) + ' MB';
  };

  const getStatusIcon = (status) => {
    switch(status) {
      case 'uploaded': return <AlertCircle className="w-4 h-4 text-blue-500" />;
      case 'processing': return <Loader className="w-4 h-4 text-yellow-500 animate-spin" />;
      case 'embedding': return <Loader className="w-4 h-4 text-purple-500 animate-spin" />;
      case 'indexed': return <CheckCircle className="w-4 h-4 text-green-500" />;
      default: return null;
    }
  };

  return (
    <div className="min-h-screen bg-gradient-to-br from-slate-50 to-slate-100">
      {/* Header */}
      <div className="bg-white border-b border-slate-200 shadow-sm">
        <div className="max-w-7xl mx-auto px-6 py-4">
          <div className="flex items-center justify-between">
            <div className="flex items-center space-x-3">
              <div className="bg-gradient-to-br from-blue-500 to-purple-600 p-2 rounded-lg">
                <Database className="w-6 h-6 text-white" />
              </div>
              <div>
                <h1 className="text-2xl font-bold text-slate-800">RAG Application</h1>
                <p className="text-sm text-slate-500">Retrieval-Augmented Generation with Local LLMs</p>
              </div>
            </div>
            <div className="flex items-center space-x-4">
              <div className="flex items-center space-x-2 bg-slate-100 px-4 py-2 rounded-lg">
                <Cpu className="w-4 h-4 text-slate-600" />
                <select 
                  value={selectedModel} 
                  onChange={(e) => setSelectedModel(e.target.value)}
                  className="bg-transparent text-sm font-medium text-slate-700 outline-none cursor-pointer"
                >
                  {availableModels.map(model => (
                    <option key={model} value={model}>{model}</option>
                  ))}
                </select>
              </div>
              <div className="bg-green-100 text-green-700 px-4 py-2 rounded-lg text-sm font-medium">
                {vectorDBStatus.indexed} vectors indexed
              </div>
            </div>
          </div>
        </div>
      </div>

      {/* Main Content */}
      <div className="max-w-7xl mx-auto px-6 py-6">
        {/* Tabs */}
        <div className="flex space-x-1 bg-white p-1 rounded-lg shadow-sm mb-6">
          <button
            onClick={() => setActiveTab('documents')}
            className={`flex-1 flex items-center justify-center space-x-2 px-4 py-3 rounded-md transition-all ${
              activeTab === 'documents' 
                ? 'bg-blue-500 text-white shadow-md' 
                : 'text-slate-600 hover:bg-slate-50'
            }`}
          >
            <FileText className="w-4 h-4" />
            <span className="font-medium">Documents</span>
          </button>
          <button
            onClick={() => setActiveTab('chat')}
            className={`flex-1 flex items-center justify-center space-x-2 px-4 py-3 rounded-md transition-all ${
              activeTab === 'chat' 
                ? 'bg-blue-500 text-white shadow-md' 
                : 'text-slate-600 hover:bg-slate-50'
            }`}
          >
            <MessageSquare className="w-4 h-4" />
            <span className="font-medium">Query & Chat</span>
          </button>
        </div>

        {/* Documents Tab */}
        {activeTab === 'documents' && (
          <div className="space-y-6">
            {/* Upload Area */}
            <div 
              onClick={() => fileInputRef.current?.click()}
              className="bg-white border-2 border-dashed border-slate-300 rounded-xl p-12 text-center cursor-pointer hover:border-blue-400 hover:bg-blue-50 transition-all"
            >
              <Upload className="w-12 h-12 text-slate-400 mx-auto mb-4" />
              <p className="text-lg font-medium text-slate-700 mb-2">Upload Documents</p>
              <p className="text-sm text-slate-500">PDF, DOCX, TXT, MD - Click to browse</p>
              <input
                ref={fileInputRef}
                type="file"
                multiple
                accept=".pdf,.docx,.txt,.md"
                onChange={handleFileUpload}
                className="hidden"
              />
            </div>

            {/* Documents List */}
            {documents.length > 0 && (
              <div className="bg-white rounded-xl shadow-sm overflow-hidden">
                <div className="px-6 py-4 border-b border-slate-200">
                  <h3 className="text-lg font-semibold text-slate-800">Uploaded Documents</h3>
                </div>
                <div className="divide-y divide-slate-100">
                  {documents.map(doc => (
                    <div key={doc.id} className="px-6 py-4 hover:bg-slate-50 transition-colors">
                      <div className="flex items-center justify-between">
                        <div className="flex items-center space-x-4 flex-1">
                          <FileText className="w-8 h-8 text-blue-500" />
                          <div className="flex-1">
                            <div className="flex items-center space-x-2">
                              <p className="font-medium text-slate-800">{doc.name}</p>
                              {getStatusIcon(doc.status)}
                            </div>
                            <div className="flex items-center space-x-4 mt-1 text-sm text-slate-500">
                              <span>{formatFileSize(doc.size)}</span>
                              {doc.chunks > 0 && <span>• {doc.chunks} chunks</span>}
                              {doc.embeddings > 0 && <span>• {doc.embeddings} embeddings</span>}
                            </div>
                          </div>
                        </div>
                        <button
                          onClick={() => handleDeleteDocument(doc.id)}
                          className="p-2 text-slate-400 hover:text-red-500 hover:bg-red-50 rounded-lg transition-colors"
                        >
                          <Trash2 className="w-5 h-5" />
                        </button>
                      </div>
                    </div>
                  ))}
                </div>
              </div>
            )}
          </div>
        )}

        {/* Chat Tab */}
        {activeTab === 'chat' && (
          <div className="bg-white rounded-xl shadow-sm flex flex-col" style={{ height: '600px' }}>
            {/* Messages Area */}
            <div className="flex-1 overflow-y-auto p-6 space-y-4">
              {messages.length === 0 ? (
                <div className="h-full flex items-center justify-center">
                  <div className="text-center">
                    <MessageSquare className="w-16 h-16 text-slate-300 mx-auto mb-4" />
                    <p className="text-slate-500 text-lg">Ask questions about your documents</p>
                    <p className="text-slate-400 text-sm mt-2">Upload documents first to get started</p>
                  </div>
                </div>
              ) : (
                messages.map(msg => (
                  <div key={msg.id} className={`flex ${msg.role === 'user' ? 'justify-end' : 'justify-start'}`}>
                    <div className={`max-w-3xl ${msg.role === 'user' ? 'bg-blue-500 text-white' : 'bg-slate-100 text-slate-800'} rounded-2xl px-5 py-3`}>
                      <p className="whitespace-pre-wrap">{msg.content}</p>
                      {msg.sources && (
                        <div className="mt-3 pt-3 border-t border-slate-200 text-xs">
                          <p className="font-medium mb-1">Sources ({msg.chunks} chunks):</p>
                          {msg.sources.map((source, idx) => (
                            <div key={idx} className="text-slate-600">• {source}</div>
                          ))}
                        </div>
                      )}
                    </div>
                  </div>
                ))
              )}
              {isQuerying && (
                <div className="flex justify-start">
                  <div className="bg-slate-100 rounded-2xl px-5 py-3">
                    <div className="flex items-center space-x-2">
                      <Loader className="w-4 h-4 animate-spin text-blue-500" />
                      <span className="text-slate-600">Retrieving context and generating answer...</span>
                    </div>
                  </div>
                </div>
              )}
              <div ref={messagesEndRef} />
            </div>

            {/* Input Area */}
            <div className="border-t border-slate-200 p-4">
              <div className="flex space-x-3">
                <input
                  type="text"
                  value={query}
                  onChange={(e) => setQuery(e.target.value)}
                  onKeyPress={(e) => e.key === 'Enter' && handleQuery()}
                  placeholder={documents.length === 0 ? "Upload documents first..." : "Ask a question about your documents..."}
                  disabled={documents.length === 0 || isQuerying}
                  className="flex-1 px-4 py-3 border border-slate-300 rounded-lg focus:outline-none focus:ring-2 focus:ring-blue-500 disabled:bg-slate-50 disabled:text-slate-400"
                />
                <button
                  onClick={handleQuery}
                  disabled={!query.trim() || documents.length === 0 || isQuerying}
                  className="px-6 py-3 bg-blue-500 text-white rounded-lg font-medium hover:bg-blue-600 disabled:bg-slate-300 disabled:cursor-not-allowed transition-colors"
                >
                  Send
                </button>
              </div>
            </div>
          </div>
        )}
      </div>
    </div>
  );
};

export default RAGApp;